# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1b877808ec759c0656328e3101163b25369a421abd47f416a1ff29aad1735eb5515a38b8ead1a379c787db64c56a1902fe8e97264850abd3ff2a49ef2bd7bb4

test:
  secret_key_base: e93c9fd503997c69727e635f663ff6614d6025e3c442d08de12d459c1e33420df1453eae33607f7d6a4964ce6561bf4a36e426398479b9294cc60d8ea0d2277a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
